--- #YAML:1.0
name:               Example-XS-FasterHashes
version:            0.01
abstract:           A tutorial with working examples for faster hashes in XS
author:
    - Daniel Dragan bulkdd cpan.org
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Time::HiRes:  0
requires:
    Time::HiRes:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
